# Generated by Django 4.1.7 on 2023-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0004_rename_phone_customer_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='bname',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='delivpart',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='finmanager',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='invman',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='delivpart',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='image',
        ),
        migrations.RemoveField(
            model_name='finmanager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='image',
        ),
        migrations.RemoveField(
            model_name='invman',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.AddField(
            model_name='delivpart',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='uploads/delivpar/'),
        ),
        migrations.AddField(
            model_name='delivpart',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='delivpart',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='finmanager',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='uploads/finman/'),
        ),
        migrations.AddField(
            model_name='finmanager',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='finmanager',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='invman',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='uploads/invman/'),
        ),
        migrations.AddField(
            model_name='invman',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AddField(
            model_name='invman',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agentimage',
            field=models.ImageField(null=True, upload_to='uploads/vendors/'),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivpart',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='finmanager',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='invman',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='invman',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(default='Koregaon', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='karsingh@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='firstname',
            field=models.CharField(default='Kartik', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='lastname',
            field=models.CharField(default='Singhania', max_length=50),
        ),
    ]
